package golang

var file = `{{$ROOT := . -}}
// Code generated by cft.

package {{.PackageName}}

import (
	"fmt"
{{- range $alias, $model := .Imports}}
	{{$model.PackageName}} "{{$model.Package}}"
{{- end}}
)

{{- range .Typedefs}}
{{template "Typedef" .}}
{{- end}}

{{- range .Constants}}
{{template "Constants" .}}
{{- end}}

{{- range .Variables}}
{{template "Variables" .}}
{{- end}}

{{- range .Functions}}
{{template "Function" .}}
{{- end}}

{{- range .Enums}}
{{template "Enum" .}}
{{- end}}

{{- range .Oneofs}}
{{template "Oneof" .}}
{{- end}}

{{- range .Structs}}
{{template "Struct" .}}
{{- end}}

{{- range .Methods}}
{{template "Method" .}}
{{- end}}
`
